---
- name: Install Wazuh Agent
  hosts: siem
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Add Wazuh repo and install agent
      shell: |
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
        echo "deb https://packages.wazuh.com/4.x/apt stable main" | tee /etc/apt/sources.list.d/wazuh.list
        apt update
        apt install wazuh-agent -y
      args:
        executable: /bin/bash

    - name: Enable and start Wazuh agent
      systemd:
        name: wazuh-agent
        enabled: yes
        state: started

    - name: Harden SSH - disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Enable UFW and allow SSH
      ufw:
        state: enabled
        rule: allow
        port: ssh
