---
- name: Deploy fail2ban
  become: yes
  hosts: all
  tasks:
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Enable and start fail2ban
      systemd:
        name: fail2ban
        enabled: yes
        state: started
