---
- name: Deploy Suricata IDS
  hosts: ids
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Suricata
      apt:
        name: suricata
        state: present

    - name: Enable and start Suricata service
      systemd:
        name: suricata
        enabled: yes
        state: started

    - name: Harden SSH - disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Enable UFW and allow SSH
      ufw:
        state: enabled
        rule: allow
        port: ssh